/**
 * @file mock-data.ts
 * @description 의료기관 스캐너용 Mock 데이터
 *
 * 실제 운영 시에는 Supabase 데이터베이스에서 데이터를 가져오도록 변경 예정
 */

import type { HospitalData } from "./types";

export const mockHospitalData: HospitalData[] = [
  {
    id: 1,
    name: "서울미소치과",
    category: "의원",
    address: "서울 강남구 테헤란로 123",
    phone: "02-123-4567",
    openDate: "2024-12-23",
    specialistCount: 3,
    sido: "서울",
    gugun: "강남구",
  },
  {
    id: 2,
    name: "행복한내과의원",
    category: "병원",
    address: "서울 서초구 서초대로 456",
    phone: "02-456-7890",
    openDate: "2024-12-22",
    specialistCount: 2,
    sido: "서울",
    gugun: "서초구",
  },
  {
    id: 3,
    name: "튼튼정형외과",
    category: "병원",
    address: "서울 송파구 올림픽로 789",
    phone: "02-789-0123",
    openDate: "2024-12-24",
    specialistCount: 4,
    sido: "서울",
    gugun: "송파구",
  },
  {
    id: 4,
    name: "맑은눈안과",
    category: "의원",
    address: "서울 강동구 천호대로 321",
    phone: "02-321-6547",
    openDate: "2025-05-10",
    specialistCount: 2,
    sido: "서울",
    gugun: "강동구",
  },
  {
    id: 5,
    name: "건강약국",
    category: "약국",
    address: "서울 마포구 양화로 159",
    phone: "02-159-7532",
    openDate: "2025-05-05",
    specialistCount: null,
    sido: "서울",
    gugun: "마포구",
  },
  {
    id: 6,
    name: "우리들한의원",
    category: "의원",
    address: "서울 용산구 이태원로 248",
    phone: "02-248-9631",
    openDate: "2025-04-30",
    specialistCount: 1,
    sido: "서울",
    gugun: "용산구",
  },
  {
    id: 7,
    name: "미래소아과의원",
    category: "의원",
    address: "서울 노원구 노해로 753",
    phone: null,
    openDate: "2025-04-25",
    specialistCount: 2,
    sido: "서울",
    gugun: "노원구",
  },
  {
    id: 8,
    name: "부산연합병원",
    category: "병원",
    address: "부산 해운대구 해운대로 123",
    phone: "051-123-4567",
    openDate: "2025-04-20",
    specialistCount: 8,
    sido: "부산",
    gugun: "해운대구",
  },
  {
    id: 9,
    name: "인천튼튼치과",
    category: "의원",
    address: "인천 연수구 센트럴로 456",
    phone: "032-456-7890",
    openDate: "2025-04-15",
    specialistCount: 3,
    sido: "인천",
    gugun: "연수구",
  },
  {
    id: 10,
    name: "대구행복약국",
    category: "약국",
    address: "대구 수성구 수성로 789",
    phone: "053-789-0123",
    openDate: "2025-04-10",
    specialistCount: null,
    sido: "대구",
    gugun: "수성구",
  },
  {
    id: 11,
    name: "광주미래안과",
    category: "의원",
    address: "광주 서구 상무대로 321",
    phone: "062-321-6547",
    openDate: "2025-04-05",
    specialistCount: 2,
    sido: "광주",
    gugun: "서구",
  },
  {
    id: 12,
    name: "대전연합의원",
    category: "병원",
    address: "대전 유성구 대학로 159",
    phone: null,
    openDate: "2025-03-30",
    specialistCount: 4,
    sido: "대전",
    gugun: "유성구",
  },
  {
    id: 13,
    name: "울산튼튼정형외과",
    category: "병원",
    address: "울산 남구 삼산로 248",
    phone: "052-248-9631",
    openDate: "2025-03-25",
    specialistCount: 3,
    sido: "울산",
    gugun: "남구",
  },
  {
    id: 14,
    name: "경기미소치과",
    category: "의원",
    address: "경기 성남시 분당구 판교로 753",
    phone: "031-753-8642",
    openDate: "2025-03-20",
    specialistCount: 4,
    sido: "경기",
    gugun: "성남시",
  },
  {
    id: 15,
    name: "서울중앙병원",
    category: "병원",
    address: "서울 중구 을지로 123",
    phone: "02-123-9876",
    openDate: "2025-03-15",
    specialistCount: 12,
    sido: "서울",
    gugun: "중구",
  },
];
